# Generated by Django 5.2.1 on 2025-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me Section', max_length=200)),
                ('bio_content', models.TextField(help_text='Your main biography and profile text.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('github', models.URLField(blank=True, max_length=500, null=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages (e.g., English, Ukrainian, Russian)', max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Your profile picture', null=True, upload_to='about_me_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me Content',
                'verbose_name_plural': 'About Me Content',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order in which achievements are displayed.')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('duration', models.CharField(help_text='e.g., 2024 - Present', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Education Entry',
                'verbose_name_plural': 'Education Entries',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Detailed description of responsibilities and achievements.')),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is a current role/education.')),
            ],
            options={
                'verbose_name': 'Work Experience Entry',
                'verbose_name_plural': 'Work Experience Entries',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('core', 'Core Skills'), ('technical', 'Technical Skills'), ('professional', 'Professional Skills'), ('other', 'Other Skills')], default='technical', help_text='Category for this skill (e.g., Technical, Core, Professional)', max_length=50)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which skills are displayed within their category.')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
