"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Ensure your .env file is in the same directory as manage.py
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# It's good practice to generate a strong key and store it in your .env
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-mfsqk+y$cdz)^f=1q_b7j-6_(et$g4_jw_9^tj%(5vriorqz6&')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production environments
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'false'

# Allowed hosts for your Django application
# In development, '127.0.0.1' and 'localhost' are typically sufficient
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Your OpenAI API Key, loaded from the .env file
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Application definition
# Add your new apps here for Django to recognize them
INSTALLED_APPS = [
    'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'portfolio',      # Your existing portfolio app
        'ai_assistant',   # Your AI Assistant app
        'blog',           # Blog app for posts
        'contact',        # Contact/Feedback form
        'about_site',     # App for About Me, Skills, Experience, and Web App Specs
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

# Templates configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS specifies a list of directories where Django should look for templates
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Points to your project-level 'templates' folder (for base.html)
        # APP_DIRS tells Django to look for 'templates' folders inside each installed app
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation for user accounts
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization settings
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC' # Consider changing to 'Europe/Dublin' for Ireland
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images) configuration
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL to serve static files (e.g., /static/css/style.css)
STATIC_URL = 'static/'
# Directories where Django's staticfiles app will look for static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Points to your project-level 'static' folder
]
# Directory where 'python manage.py collectstatic' will gather all static files for deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected')


# Media files (user uploaded content via admin, like project images)
# URL for serving media files
MEDIA_URL = '/media/'
# Absolute path to the directory where uploaded media files will be stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Email Configuration for Feedback Form ---
# IMPORTANT: For actual email sending, you would use a real SMTP server.
# These settings use Django's console email backend for testing purposes (emails print to terminal).
# Change to 'django.core.mail.backends.smtp.EmailBackend' for production.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # CHANGE THIS LINE FOR LIVE EMAIL
# Uncomment and configure these for actual email sending:
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com') # Example for Gmail
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # Your sending email address (e.g., 555future777@gmail.com)
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # Your email app password (NOT your regular password)

# The email address that feedback/offers will appear to come from
DEFAULT_FROM_EMAIL = '555future777@gmail.com' # Your actual email address
