# Generated by Django 5.2.1 on 2025-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('app_link', models.URLField(blank=True, help_text='Link to the live application (if deployed)', max_length=500, null=True)),
                ('github_link', models.URLField(blank=True, help_text='Link to the GitHub repository', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, help_text='Thumbnail image for the project', null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
